### ISSUE TITLE
没有任何文件操作,提示文件被使用

### ISSUE THREAD

**Issue by lanyi1998** [TheKingOfDuck/webInfoScan#1]
PermissionError: [WinError 32] 另一个程序正在使用此文件，进程无法访问。: 'C:\\Us
ers\\Administrator\\Desktop\\domain_screen/urls.txt'

**Comment by ST0new** [comment]
me too

**Comment by dd404x** [comment]
me too

**Comment by TheKingOfDuck** [comment]
文本还被其他进程占用着，和这个程序没啥关系。
另外，这个程序没在Windows上测过，也没打算兼容Windows，首先macOS，其他系统上的bug不考虑修复（因为懒）
